site_title: Transport Denis Corbeil
site_email: info@transportdeniscorbeil.com
site_tel: 450-258-0772
site_fax: 450-258-1695
site_address: |-
  13450 Rte Arthur-Sauvé,

  Mirabel (QC) J7N 2C1
site_business_hours: 'Lundi au Vendredi, 8h00 à 16h30'
