backend:

  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img"

collections:

  - name: "special-pages"
    label: "Éditer le contenu des pages"
    delete: false # Prevent users from deleting documents in this collection
    files:
      - name: "home"
        file: "index.md"
        label: "Éditer la page d'accueil"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Titre de la page", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description (Google)", name: "description", widget: "string"}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - {label: "Slogan1", name: "slogan1", widget: "string"}
          - {label: "Slogan2", name: "slogan2", widget: "string"}

          - {label: "Icone 1", name: "icon1", widget: "image"}
          - {label: "Paragraphe 1", name: "text1", widget: "string"}
          - {label: "Texte du lien 1", name: "link1", widget: "string"}
          - {label: "Lien 1", name: "url1", widget: "string"}

          - {label: "Icone 2", name: "icon2", widget: "image"}
          - {label: "Paragraphe 2", name: "text2", widget: "string"}
          - {label: "Texte du lien 2", name: "link2", widget: "string"}
          - {label: "Lien 2", name: "url2", widget: "string"}

          - {label: "Icone 3", name: "icon3", widget: "image"}
          - {label: "Paragraphe 3", name: "text3", widget: "string"}
          - {label: "Texte du lien 3", name: "link3", widget: "string"}
          - {label: "Lien 3", name: "url3", widget: "string"}

      - name: "a-propos"
        file: "a-propos.md"
        label: "Éditer la page À propos"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Titre de la page", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", default: "/a-propos", widget: "hidden" }
          - {label: "Description (Google)", name: "description", widget: "string"}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - {label: "Contenu", name: "body", widget: "markdown"}
          - {label: "Image 1", name: "image1", widget: "image"}

      - name: "services"
        file: "services.md"
        label: "Éditer la page des Services"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "services"}
          - {label: "Titre de la page", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", default: "/services", widget: "hidden" }
          - {label: "Description (Google)", name: "description", widget: "string"}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - {label: "Contenu", name: "body", widget: "markdown"}
          - {label: "Image 1", name: "image1", widget: "image"}

      - name: "vehicules"
        file: "vehicules.md"
        label: "Éditer la page des Véhicules"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "vehicules"}
          - {label: "Titre de la page", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", default: "/vehicules", widget: "hidden" }
          - {label: "Description (Google)", name: "description", widget: "string"}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - {label: "Contenu", name: "body", widget: "markdown", required: false}
          - label: "Véhicules"
            name: "gallery"
            widget: "list"
            required: false
            fields:
              - {label: "Titre de l'image", name: "image_title", widget: string }
              - {label: "Image", name: "image", widget: image }

      - name: "contact"
        file: "contact.md"
        label: "Éditer la page Contact"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "services"}
          - {label: "Titre de la page", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", default: "/services", widget: "hidden" }
          - {label: "Description (Google)", name: "description", widget: "string"}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - {label: "Contenu", name: "body", widget: "markdown"}

      - name: "emplois"
        file: "emplois.md"
        label: "Éditer la page des Emplois"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "emplois"}
          - {label: "Titre de la page", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", default: "/emplois", widget: "hidden" }
          - {label: "Description (Google)", name: "description", widget: "string"}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - {label: "Contenu", name: "body", widget: "markdown", required: false}
          - label: "Emplois"
            name: "jobs"
            widget: "list"
            required: false
            fields:
              - {label: "Titre de l'emploi", name: "job_title", widget: string }
              - {label: "Date de l'affichage", name: "job_date", widget: date }
              - {label: "Salaire", name: "job_salary", widget: string }
              - {label: "Description", name: "job_desc", widget: markdown }



  - name: "settings"
    label: "Paramètres du site"
    delete: false # Prevent users from deleting documents in this collection
    editor:
     preview: false
    files:
       - name: "general"
         label: "Général"
         file: "_data/settings.yml"
         description: "Paramètres Généraux"
         fields:
           - {label: "Titre du site", name: "site_title", widget: "string"}
           - {label: "Courriel de contact", name: "site_email", widget: "string", required: false}
           - {label: "Numéro de téléphone", name: "site_tel", widget: "string", required: false}
           - {label: "Numéro de fax", name: "site_fax", widget: "string", required: false}
           - {label: "Addresse de l'entreprise", name: "site_address", widget: "markdown", required: false}
           - {label: "Heures d'ouverture", name: "site_business_hours", widget: "string", required: false}
           - {label: "Lien vers page Facebook", name: "url_facebook", widget: "string", required: false}
           - {label: "Lien vers page Instagram", name: "url_instagram", widget: "string", required: false}
